<Struct>
<Identifier("Point")>
<Newline>
<Identifier("x")>
<TypeDef>
<Identifier("Int")>
<Newline>
<Identifier("y")>
<TypeDef>
<Identifier("Int")>
<Newline>
<End>
<Newline>
<Newline>
<Identifier("a")>
<Assignment>
<Identifier("Point")>
<LParen>
<Int(1)>
<Comma>
<Int(2)>
<RParen>
<Newline>
<Identifier("b")>
<TypeDef>
<Identifier("Point")>
<Assignment>
<Identifier("new")>
<LParen>
<Colon>
<Identifier("Point")>
<Comma>
<Int(3)>
<Comma>
<Int(4)>
<RParen>
<Newline>
<Newline>
<Identifier("printf")>
<LParen>
<StringLiteral("'a' pointer: %p\n")>
<Comma>
<Identifier("a")>
<RParen>
<Newline>
<Identifier("printf")>
<LParen>
<StringLiteral("a.x manual (pointer): %p\n")>
<Comma>
<Identifier("a")>
<Plus>
<Int(0)>
<RParen>
<Newline>
<Identifier("printf")>
<LParen>
<StringLiteral("a.x manual (mem_load pointer): %p\n")>
<Comma>
<Identifier("_mem_load")>
<LParen>
<Identifier("a")>
<Comma>
<Int(0)>
<RParen>
<RParen>
<Newline>
<Identifier("printf")>
<LParen>
<StringLiteral("a.x manual (mem_load int): %d\n")>
<Comma>
<Identifier("_mem_load")>
<LParen>
<Identifier("a")>
<Comma>
<Int(0)>
<RParen>
<RParen>
<Newline>
<Identifier("printf")>
<LParen>
<StringLiteral("a.y manual (pointer): %p\n")>
<Comma>
<Identifier("a")>
<Plus>
<Int(8)>
<RParen>
<Newline>
<Identifier("printf")>
<LParen>
<StringLiteral("a.y manual (mem_load pointer): %p\n")>
<Comma>
<Identifier("_mem_load")>
<LParen>
<Identifier("a")>
<Comma>
<Int(8)>
<RParen>
<RParen>
<Newline>
<Identifier("printf")>
<LParen>
<StringLiteral("a.y manual (mem_load int): %d\n")>
<Comma>
<Identifier("_mem_load")>
<LParen>
<Identifier("a")>
<Comma>
<Int(8)>
<RParen>
<RParen>
<Newline>
<Newline>
<Identifier("printf")>
<LParen>
<StringLiteral("X (int): %d\n")>
<Comma>
<Identifier("a")>
<Dot>
<Identifier("x")>
<RParen>
<Newline>
<Identifier("printf")>
<LParen>
<StringLiteral("Y (int): %d\n")>
<Comma>
<Identifier("a")>
<Dot>
<Identifier("y")>
<RParen>
<Newline>
<Newline>
<Identifier("printf")>
<LParen>
<StringLiteral("'b' pointer: %p\n")>
<Comma>
<Identifier("b")>
<RParen>
<Newline>
<Identifier("printf")>
<LParen>
<StringLiteral("b.x manual (pointer): %p\n")>
<Comma>
<Identifier("b")>
<Plus>
<Int(0)>
<RParen>
<Newline>
<Identifier("printf")>
<LParen>
<StringLiteral("b.x manual (mem_load pointer): %p\n")>
<Comma>
<Identifier("_mem_load")>
<LParen>
<Identifier("b")>
<Comma>
<Int(0)>
<RParen>
<RParen>
<Newline>
<Identifier("printf")>
<LParen>
<StringLiteral("b.x manual (mem_load int): %d\n")>
<Comma>
<Identifier("_mem_load")>
<LParen>
<Identifier("b")>
<Comma>
<Int(0)>
<RParen>
<RParen>
<Newline>
<Identifier("printf")>
<LParen>
<StringLiteral("b.y manual (pointer): %p\n")>
<Comma>
<Identifier("b")>
<Plus>
<Int(8)>
<RParen>
<Newline>
<Identifier("printf")>
<LParen>
<StringLiteral("b.y manual (mem_load pointer): %p\n")>
<Comma>
<Identifier("_mem_load")>
<LParen>
<Identifier("b")>
<Comma>
<Int(8)>
<RParen>
<RParen>
<Newline>
<Identifier("printf")>
<LParen>
<StringLiteral("b.y manual (mem_load int): %d\n")>
<Comma>
<Identifier("_mem_load")>
<LParen>
<Identifier("b")>
<Comma>
<Int(8)>
<RParen>
<RParen>
<Newline>
<Newline>
<Identifier("printf")>
<LParen>
<StringLiteral("X (int): %d\n")>
<Comma>
<Identifier("b")>
<Dot>
<Identifier("x")>
<RParen>
<Newline>
<Identifier("printf")>
<LParen>
<StringLiteral("Y (int): %d\n")>
<Comma>
<Identifier("b")>
<Dot>
<Identifier("y")>
<RParen>
