[package]
name = "Errand"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
cranelift-frontend = "0.121.1"
cranelift-codegen = "0.121.1"
cranelift-module = "0.121.1"
cranelift = "0.121.1"
cranelift-native = "0.121.1"
cranelift-object = "0.121.1"
