<Identifier("foreign")>
<Function>
<Identifier("printf")>
<LParen>
<Identifier("a")>
<TypeDef>
<Identifier("Int")>
<RParen>
<TypeDef>
<Identifier("Int")>
<Newline>
<Identifier("foreign")>
<Function>
<Identifier("malloc")>
<LParen>
<Identifier("a")>
<TypeDef>
<Identifier("Int")>
<RParen>
<TypeDef>
<Identifier("Int")>
<Newline>
<Identifier("foreign")>
<Function>
<Identifier("free")>
<LParen>
<Identifier("a")>
<TypeDef>
<Identifier("Int")>
<RParen>
<TypeDef>
<Identifier("Int")>
<Newline>
<Identifier("foreign")>
<Function>
<Identifier("strlen")>
<LParen>
<Identifier("a")>
<TypeDef>
<Identifier("Int")>
<RParen>
<TypeDef>
<Identifier("Int")>
<Newline>
<Identifier("foreign")>
<Function>
<Identifier("strcpy")>
<LParen>
<Identifier("a")>
<TypeDef>
<Identifier("Int")>
<Comma>
<Identifier("b")>
<TypeDef>
<Identifier("Int")>
<RParen>
<TypeDef>
<Identifier("Int")>
<Newline>
<Identifier("foreign")>
<Function>
<Identifier("strcmp")>
<LParen>
<Identifier("a")>
<TypeDef>
<Identifier("Int")>
<Comma>
<Identifier("b")>
<TypeDef>
<Identifier("Int")>
<RParen>
<TypeDef>
<Identifier("Int32")>
<Newline>
<Newline>
<Function>
<Identifier("strlen")>
<LParen>
<Identifier("a")>
<TypeDef>
<Identifier("String")>
<RParen>
<Newline>
<Return>
<Identifier("strlen")>
<LParen>
<Identifier("as_ptr")>
<LParen>
<Identifier("a")>
<RParen>
<RParen>
<Newline>
<End>
<Newline>
<Newline>
<Identifier("printf")>
<LParen>
<StringLiteral("Hello World!")>
